# Generated by Django 4.1.5 on 2023-02-08 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clips', '0002_alter_clip_clipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='v_link',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clip',
            name='viewers',
            field=models.ManyToManyField(related_name='viewer', to=settings.AUTH_USER_MODEL, verbose_name='viewer'),
        ),
        migrations.AlterField(
            model_name='clip',
            name='clipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clipper', to=settings.AUTH_USER_MODEL, verbose_name='clipper'),
        ),
    ]
