# Generated by Django 4.1.5 on 2023-05-24 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clips', '0004_alter_clip_viewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='viewers',
        ),
        migrations.AddField(
            model_name='clip',
            name='viewers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewer', to=settings.AUTH_USER_MODEL, verbose_name='viewer'),
        ),
    ]
