# Generated by Django 4.1.5 on 2023-05-24 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clips', '0005_remove_clip_viewers_clip_viewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='viewers',
        ),
        migrations.AddField(
            model_name='clip',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewer', to=settings.AUTH_USER_MODEL, verbose_name='viewer'),
        ),
    ]
