# Generated by Django 4.1.5 on 2023-02-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_game_mimage'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='games_downloaded',
            field=models.ManyToManyField(to='games.game', verbose_name='games_downloaded'),
        ),
    ]
