# Generated by Django 4.1.5 on 2023-02-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
        ('accounts', '0002_profile_games_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clips',
            field=models.ManyToManyField(to='clips.clip', verbose_name='clips'),
        ),
    ]
