# Generated by Django 4.1.5 on 2023-02-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_game_mimage'),
        ('clips', '0001_initial'),
        ('accounts', '0003_profile_clips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='clips',
            field=models.ManyToManyField(blank=True, null=True, to='clips.clip', verbose_name='clips'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='games_downloaded',
            field=models.ManyToManyField(blank=True, null=True, to='games.game', verbose_name='games_downloaded'),
        ),
    ]
