# Generated by Django 4.1.5 on 2023-02-09 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='clips',
        ),
    ]
