# Generated by Django 4.1.5 on 2023-02-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_game_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='data_added',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
    ]
