# Generated by Django 4.1.5 on 2023-02-09 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0014_alter_game_data_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='downloaders',
            field=models.ManyToManyField(related_name='games', to=settings.AUTH_USER_MODEL),
        ),
    ]
