# Generated by Django 4.1.5 on 2023-02-09 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_game_downloaders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='games.game'),
        ),
    ]
