# Generated by Django 4.1.5 on 2023-02-09 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0017_game_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='downloaders',
            field=models.ManyToManyField(blank=True, null=True, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
    ]
