# Generated by Django 4.1.5 on 2023-02-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_alter_game_downloaders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='data_added',
            field=models.DateField(auto_created=True, auto_now=True, null=True),
        ),
    ]
