# Generated by Django 4.1.5 on 2023-05-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0023_alter_game_downloaders_alter_game_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
    ]
