# Generated by Django 4.1.5 on 2023-05-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_alter_game_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gamefile',
            field=models.FileField(blank=True, null=True, upload_to='Games/%d/'),
        ),
    ]
