# Generated by Django 4.1.5 on 2023-05-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0025_game_gamefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mimage',
            field=models.FileField(blank=True, null=True, upload_to='Games/main-images/%d/'),
        ),
    ]
