# Generated by Django 4.1.5 on 2023-05-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0026_alter_game_mimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Images/%d/'),
        ),
    ]
