# Generated by Django 4.1.5 on 2023-05-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_remove_image_url_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='video',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
