# Generated by Django 4.1.5 on 2023-02-09 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streams', '0002_stream_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='streamer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='stream', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stream',
            name='viewers',
            field=models.ManyToManyField(related_name='stream_viewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
