# Generated by Django 4.1.5 on 2023-02-09 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_game_downloaders'),
        ('streams', '0005_stream_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='games.game'),
        ),
    ]
