# Generated by Django 4.1.5 on 2023-05-24 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('streams', '0007_alter_stream_streamer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='stream_viewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
